### ISSUE TITLE
error in convert model

### ISSUE THREAD

**Issue by nova-synova** [axodox/unpaint#46]
when i follow the guide of Model-import, then run "python .\stable_diffusion.py --optimize --model_id runwayml/stable-diffusion-v1-5" in "olive-sd\olive\examples\directml\stable_diffusion" directory, report error as follow:

(olive-env) PS D:\E_2_D\temp\axodox\olive-sd\olive\examples\directml\stable_diffusion> python .\stable_diffusion.py --optimize --model_id runwayml/stable-diffusion-v1-5
C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\pydantic\_internal\_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'json_dumps' has been removed
* 'json_loads' has been removed
  warnings.warn(message, UserWarning)
C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\pydantic\_internal\_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'json_dumps' has been removed
* 'json_loads' has been removed
  warnings.warn(message, UserWarning)
C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\pydantic\_internal\_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'json_dumps' has been removed
* 'json_loads' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File ".\stable_diffusion.py", line 18, in <module>
    from olive.workflows import run as olive_run
  File "C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\olive\workflows\__init__.py", line 5, in <module>
    from olive.workflows.run.run import run
  File "C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\olive\workflows\run\run.py", line 16, in <module>
    from olive.passes import Pass
  File "C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\olive\passes\__init__.py", line 5, in <module>
    from olive.passes.olive_pass import FullPassConfig, Pass
  File "C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\olive\passes\olive_pass.py", line 13, in <module>
    from olive.common.config_utils import ConfigBase, validate_config
  File "C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\olive\common\config_utils.py", line 118, in <module>
    class ConfigListBase(ConfigBase):
  File "C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\pydantic\_internal\_model_construction.py", line 98, in __new__
    private_attributes = inspect_namespace(
  File "C:\Users\synov\miniconda3\envs\olive-env\lib\site-packages\pydantic\_internal\_model_construction.py", line 291, in inspect_namespace
    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
(olive-env) PS D:\E_2_D\temp\axodox\olive-sd\olive\examples\directml\stable_diffusion>

**Comment by hpolkowski** [comment]
Hi, pydantic V2 changed a lot. You can uninstall it `pip uninstall pydantic` and install V1 `pip install pydantic==1.10.7`.

**Comment by nova-synova** [comment]
thanks, it works now.
